### ISSUE TITLE
Black Screen in Wario Land Shake it! after creating a .gfa file

### ISSUE THREAD

**Issue by evil-trainer** [Swiftshine/Tangle#8]
Hello!

I used Tangle to extract and create Wario Land Shake it! .gfa files but despite it showing a succesful message after finishing its process, I couldn't make the newly generated file work in the game. I'm a fan translator, so I'm trying to translate the texts and textures of the game, but whenever I create the .gfa files I get a black screen in-game.

![image](https://github.com/user-attachments/assets/291c1108-91a9-4a80-81ae-6420543d7c1a)

I noticed the files generated by Tangle have smaller sizes then their original counterparts. I'm not sure if that's expected or if it may be causing all the issues I'm having. I did everything according to the instructions in here (specially setting the 2.0 thing after creating a .gfa).

I'm sending a coulpe sample files in hopes they may help track down the issue with them. Thanks in advance and congrats on the awesome tool Tangle is!
[__PACK__.zip](https://github.com/user-attachments/files/18268522/__PACK__.zip) (Text strings for the game)
[__PACK__.zip](https://github.com/user-attachments/files/18268525/__PACK__.zip) (Textures for the Title Screen)

**Comment by Swiftshine** [comment]
Hello! I've been busy, but I've planned to do a rewrite of this in Rust for a while now, since I've written a crate for the GfArch format. I'll get back to you once I do that.

**Comment by evil-trainer** [comment]
> Hello! I've been busy, but I've planned to do a rewrite of this in Rust for a while now, since I've written a crate for the GfArch format. I'll get back to you once I do that.

Thank you very much! I can't wait to test it! 😁 👍🏼

**Comment by Swiftshine** [comment]
I've completed my rewrite, and hopefully the experience should be much cleaner. You can download the newest release  now. Let me know if archiving works for you yet.

**Comment by evil-trainer** [comment]
OMG, so fast! I'll test it out in a bit! Thank you so much! 😁

**Comment by evil-trainer** [comment]
It worked like a charm! Thank you SO MUCH! I'll credit you on my translation once I finish it!

![2024-12-29 (6)](https://github.com/user-attachments/assets/2bccbb74-4818-47f8-b736-8858874e6119)
![2024-12-29 (7)](https://github.com/user-attachments/assets/f80ca1ed-ce9b-4a56-9101-7be01f07674c)
![2024-12-29 (8)](https://github.com/user-attachments/assets/6d52754b-50cf-4f4e-af7b-7f9b0b45836a)
